### ISSUE TITLE
Jira Search Connector is Not Working

### ISSUE THREAD

**Issue by natalie-pienkowska** [microsoft/PowerPlatformConnectors#1005]
**Type of Connector**

- [ ] certified 
- [ ] custom 
- [x] independent publisher

**Name of Connector** 
Jira Search by Paul Culmsee

**Describe the bug**
The connector is failing and has 0 successful runs. Majority of the failures are at invoking backend/JIRA APIs. Connector owner needs to check if they set the backend url properly.

**Is this a security bug?**
- [ ] yes
- [x] no

**What is the severity of this bug?**
- [x] severity 1: Connector is broken or there's a very serious issue
- [ ] severity 2: One or more important connector features are down
- [ ] severity 3: Minor issue

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
We expect the connector to work.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`paconn --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**
![jirasearchbroken](https://user-images.githubusercontent.com/73195764/128215905-61a9d15d-620c-46f6-8b41-edb1a943acdb.PNG)

First column refers to active connections, second is requests, last is successful calls.

**Comment by paulculmsee** [comment]
I just did a successful test of it at client site. Most likely issue is hostname param is not being set right. Make sure it is just the host name and not fqdn, eg..

![image](https://user-images.githubusercontent.com/4979626/128312532-839af940-3ecd-42c6-b91b-64876d19f982.png)

and definitely NOT

![image](https://user-images.githubusercontent.com/4979626/128312627-2294def4-27d7-4a45-861e-98d698275a24.png)

**Comment by mmurshed** [comment]
@natalie-pienkowska does this resolve the issue? @paulculmsee can you update the readme?

**Comment by natalie-pienkowska** [comment]
Thanks, @paulculmsee, for clarifying. That totally makes sense. If you could add that to the readme.md, we'll we'll add that to the public docs :)

**Comment by natalie-pienkowska** [comment]
Paul has updated the readme
