### ISSUE TITLE
HubSpot CMS | Response schema is missing

### ISSUE THREAD

**Issue by Laskewitz** [microsoft/PowerPlatformConnectors#1035]
**Type of Connector**

- [ ] certified 
- [ ] custom 
- [x] independent publisher

**Name of Connector**
HubSpot CMS

**Describe the bug**
The response schema is missing, which means no dynamic content is shown as outputs and makers have to use parse JSON to parse the response.

**Is this a security bug?**
- [ ] yes
- [x] no

**What is the severity of this bug?**
- [x] severity 1: Connector is broken or there's a very serious issue
- [ ] severity 2: One or more important connector features are down
- [ ] severity 3: Minor issue

**To Reproduce**
Create a flow with a button trigger, add an action, add a compose action, and the output only shows a body object from the action before the compose.

**Expected behavior**
Create a flow with a button trigger, add an action, add a compose action, and the output should show properties from the action before the compose.

**Comment by natalie-pienkowska** [comment]
@Laskewitz thanks again for submitting this issue and for making sure that we are producing great connectors with little to no barrier of entry. @troystaylor and our team has tried implementing this with C# code, but unfortunately the responses are dynamic and there is no way to add schemas that would work for all.
