### ISSUE TITLE
[BUG] Custom Connector Swagger Error: Definition Schemas Count Exceeds 512

### ISSUE THREAD

**Issue by troystaylor** [microsoft/PowerPlatformConnectors#1088]
### Type of Connector

Independent Publisher Connector

### Name of Connector

Xero Accounting

### Describe the bug

I am unable to save a service-provided API file that has been converted to YAML due to the service's use of definitions. I keep receiving errors when saving that have this same value for each definition:

Specified swagger has the following errors: 'Definition is not valid.  Error: 'Critical : definitions/{Definition} : The total number of schemas in the object exceeds the max schema count allowed value of '512'. Please remove any unnecessary property or item definitions.

Is this due to a Power Automate custom connector specification or a Swagger specification? I cannot find details that this is due to Swagger.

### Is this a security bug?

No, this is not a security bug

### What is the severity of this bug?

Severity 2 - One or more important connector features are down

### To Reproduce

1. Import connector from https://raw.githubusercontent.com/XeroAPI/Xero-OpenAPI/master/xero_accounting.yaml
2. Fix other errors, then try to save.

### Expected behavior

Definitions should be able to have more that 512 values

### Environment summary

Dev environment using the standard Power Automate custom connector editor

### Additional context

None that I can think of

**Comment by natalie-pienkowska** [comment]
Hi @troystaylor thanks for submitting this issue. As we discussed on Tuesday, this is a platform limitation. We will be working to add this limitation to our documentation.

**Comment by ccpauto** [comment]
This is a well published limit: 
https://docs.microsoft.com/connectors/custom-connectors/faq#limits
Please make use of a dynamic schema if possible or prune the unimportant parts of schema.
