### ISSUE TITLE
[BUG] OptiApi actions always throw "unauthenticated" error 

### ISSUE THREAD

**Issue by tszalaj** [microsoft/PowerPlatformConnectors#1098]
### Type of Connector

Independent Publisher Connector

### Name of Connector

OptiAPI

### Describe the bug

API tokens generated in OptiAPI control panel don't work in PowerAutomate connections - actions always throw "Unauthenticated" error. 

### Is this a security bug?

No, this is not a security bug

### What is the severity of this bug?

Severity 1 - Connector is broken or there's a very serious issue

### To Reproduce

1. Create free OptiAPI account
2. Log in to service control panel - API section: https://optiapi.com/settings#/api
3. Create API token and copy it to the clipboard
4. Create a new flow started with button and one OptiApi action - ie. "Replace text in string" 
5. Create connection with your e-mail address as connection name and paste API key from service control panel
6. Enter 3 strings as action params
5. Start the flow
6. You get "Unauthenticated" error.

### Expected behavior

Activity should return result - text with replaced string according to the parameters.

### Environment summary

nothing special :) only new flow in power automate

### Additional context

I've tried to contact the vendor through "email me" function in OptiAPI control panel, but the form doesn't work - it doesn't send e-mail.

**Comment by natalie-pienkowska** [comment]
Thank you for letting us know about this issue, @tszalaj. Since this issue pertains to a certified connector, @ptalrejagithub will engage with the partner directly.

**Comment by natalie-pienkowska** [comment]
Hi @oliverbj! It looks like an issue has been reported for your OptiApi connector. Do you mind taking a look and helping resolve it, please? 

@ptalrejagithub for awareness.

**Comment by natalie-pienkowska** [comment]
Hi @tszalaj do you mind trying out what Oliver has proposed above?

**Comment by tszalaj** [comment]
I did it and activity worked. However this is not satisfying solution. When creating OptiAPI connection, user is prompted to insert API Key. There is also a hint "Provide your API Key" - not "Provide your API key after word 'Bearer' without quotes". If I need to post a bug on Power Platform Connectors forum to get this basic information how to create a valid connection to this service, then it should be fixed or a connector should not be certified.

![image](https://user-images.githubusercontent.com/22726739/150138217-203b6559-366f-4d95-940a-b37b7ec073ba.png)

**Comment by oliverbj** [comment]
> I did it and activity worked. However this is not satisfying solution. When creating OptiAPI connection, user is prompted to insert API Key. There is also a hint "Provide your API Key" - not "Provide your API key after word 'Bearer' without quotes". If I need to post a bug on Power Platform Connectors forum to get this basic information how to create a valid connection to this service, then it should be fixed or a connector should not be certified.
> 
> ![image](https://user-images.githubusercontent.com/22726739/150138217-203b6559-366f-4d95-940a-b37b7ec073ba.png)

OptiAPI have a documentation part for all our API endpoints, where this is documented:

![image](https://user-images.githubusercontent.com/7851696/150142094-f0a33ec6-1666-4cd7-bf73-c28f3d10aa54.png)

I agree, the documentation around this could be more explicit in Power Automate.

**Comment by tszalaj** [comment]
Well, this is not user friendly solution, especially when you actually can add word "Bearer" to the API key when it's not present. But at least this thread explains what to do with the Unauthenticated error.
