### ISSUE TITLE
Freshservice connector showing html tags in ticket description

### ISSUE THREAD

**Issue by glavincrasta10** [microsoft/PowerPlatformConnectors#1105]
A CX has pointed out that the Freshservice connector is not removing the html tags from the description sent into the ticket. This is working properly for Freshdesk connector but for Freshservice there seems to be an issue.
![image003](https://user-images.githubusercontent.com/90756201/133396543-d1893c93-9990-4c27-9138-98270923b7f3.png)

**Comment by natalie-pienkowska** [comment]
Hi @glavincrasta10! Thank you for submitting this bug for the FreshService connector. @ptalrejagithub will reach out to the partner to notify them about this issue and figure out a workaround or solution.

**Comment by natalie-pienkowska** [comment]
Hi @glavincrasta10 we just wanted to let you know that we have added this bug to our backlog and will prioritize accordingly. I will now be closing this issue.
