### ISSUE TITLE
Swagger Validator and paconn tool doesn't check for 'content_type' syntax

### ISSUE THREAD

**Issue by v-sriyen** [microsoft/PowerPlatformConnectors#118]
**Describe the bug**
Swagger Validator doesn't check for 'content_type' syntax in the swagger

**To Reproduce**
Below Swagger passed paconn tool and Swagger Validator
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "default": {
                **"conten_type"**: "sdsd",
                "encoding": "cp1251"
              },
              "properties": {
                **"conten_type"**: {
                  "description": "conten_type",
                  "title": "Content type",
                  "type": "string"
                },
                "encoding": {
                  "description": "encoding",
                  "enum": [
                    "cp1251",
                    "cp866",
                    "utf-8"
                  ],
                  "title": "Encoding",
                  "type": "string"
                }
              },
              "required": [
                "conten_type",
                "encoding"
              ],
              "type": "object"
            }
          }

**Expected behavior**
The paconn and Swagger Validator should validate the content_type and its value. Please close the bug if this is a design of the tools.

**Comment by mamurshe** [comment]
@v-sriyen cli is just a client for the swagger validator. Please submit the defect to the internal bug tracker.
