### ISSUE TITLE
Paconn - Is there a way to create Windows Authentication using On-prem Gateway

### ISSUE THREAD

**Issue by Chris-Dussourd** [microsoft/PowerPlatformConnectors#1259]
Type of Connector
Custom Connector

Describe the enhancement
Only Basic Authentication, API Key, and OAuth2 seem to be supported when creating a Custom Connector through paconn. Windows Authentication is an option that appears only when connecting through the on-premises gateway.

Is this a security bug?
No, this is not a security bug

To Reproduce
paconn create -s settings.json

Expected behavior
![image](https://user-images.githubusercontent.com/60725155/141491398-891372bd-8384-425b-b1e4-c839000c27c7.png)

Paconn version : 0.0.19

Additional context
NA

**Comment by natalie-pienkowska** [comment]
Hi @Chris-Dussourd thank you so much for raising this feature request! We have added it to our backlog and prioritized it accordingly.
