### ISSUE TITLE
CQC Data Connector Swagger String

### ISSUE THREAD

**Issue by natalie-pienkowska** [microsoft/PowerPlatformConnectors#1386]
### Type of Connector

Independent Publisher Connector

### Name of Connector

CQC Data

### Describe the bug

The localization translator flagged a string with very poor syntax, missing periods in the whole segment. Could it be possible to update the source?  Many thanks!

"The Changes service provides a mechanism of staying informed about updates to providers and locations, to allow users to refresh their cached data if necessary Changes for two organisation types are available: provider or location API consumers must specify a start and end date range, see the API reference for more detail This service allows identification of which organisations have changed over time For successive calls to this service, the startTime parameter should be set to the endTime of the previous call The times correspond to the time that this service itself acquires the data and is not, for example, the time of data entry onto a source system"

### Is this a security bug?

No, this is not a security bug

### What is the severity of this bug?

Severity 3 - Minor issue

### To Reproduce

In the swagger file. 

### Expected behavior

Should be concise sentences with punctuation.

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build)
CLI version (paconn --version)
OS version
Shell Type (e.g. bash, cmd.exe, Bash on Windows)

### Additional context

N/A

**Comment by troystaylor** [comment]
PR submitted: https://github.com/microsoft/PowerPlatformConnectors/pull/1387

**Comment by natalie-pienkowska** [comment]
Thanks so much @troystaylor :) This change helped us localize this connector!
