### ISSUE TITLE
Looks like you changed the folder structure, which broke links In Power Automate documentation

### ISSUE THREAD

**Issue by pzerger** [microsoft/PowerPlatformConnectors#142]
**Describe the bug**
Broken links in Power Automate docs due to folder changes in this repo.

**To Reproduce**
Click on links references this repo on this page - https://docs.microsoft.com/en-us/connectors/facebook/

**Expected behavior**
You may want to check with Docs team to figure out how impactful this is across all Power Platform docs.

**Environment summary**
Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`paconn --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

**Additional context**

**Comment by dougelliott** [comment]
Hey @pzerger - thanks for flagging this. From what I can find this seems to be the only instance of impact. We'll make an item to get this addressed.

**Comment by dougelliott** [comment]
@pzerger I've put in the change to fix the link in the Facebook documentation. That'll go out with the next deployment cycle in a few business days. I'll go ahead and consider this resolved, and close the issue accordingly.

Thanks again for flagging!
