### ISSUE TITLE
[paconn download] apiProperties.json should not emit internal properties

### ISSUE THREAD

**Issue by joem-msft** [microsoft/PowerPlatformConnectors#146]
**Describe the bug**
When downloading the connection parameters for a connector, certain properties of the oAuthSettings object should not be saved, as these are output properties, not input properties.

**To Reproduce**
paconn download for any connector that uses oauthsettings tokens.

**Expected behavior**
the following properties under the oAuthSettings object should not be saved:
- redirectUrl
- properties - This is an object which has only internal, client values. e.g. '/properties/IsFirstParty'

**Comment by natalie-pienkowska** [comment]
Thanks @joem-msft for submitting this issue. We have added it to our backlog and will prioritize accordingly.
