### ISSUE TITLE
[paconn] simplify paconn create/update commands so filenames are assumed to be the expected folder layout filenames

### ISSUE THREAD

**Issue by joem-msft** [microsoft/PowerPlatformConnectors#147]
**Describe the bug**
The names of these files should be assumed if not specified. The filenames already have defaults in the settings.py file. We shoudn't have to specify them on the cmd line or explicitly in the settings.json file. Instead, they should use the same default values.

While the repro steps describe one of the ways this behavior shows up, the ask here is to make it so that adherence to the folder structure and filenames results in simpler command execution.

**To Reproduce**
1. cd into an existing connector's folder (e.g. certified-connectors\AzureAD)
1. create a settings.json file with the following content:
```json
{
  "connectorId": "myAzureAD"
}
```
3. run the command `paconn create -s settings.json`
  a. When prompted, select an environment and hit enter.

**Expected behavior**
A custom connector should've been created successfully.

**Actual Behavior**
An error occurs stating: `API Properties must be specified.`

**Comment by natalie-pienkowska** [comment]
Adding this to our repair item backlog. Thank you again for raising this issue @joem-msft
