### ISSUE TITLE
[FEATURE REQUEST] Move to Snowflake SQL API v2

### ISSUE THREAD

**Issue by sfc-gh-ngoodman** [microsoft/PowerPlatformConnectors#1485]
### Type of Connector

Custom Connector

### Name of Connector

Snowflake

### Is your feature request related to a problem? Please describe.

Snowflake had early access to this API feature (v1) and is releasing into GA a different endpoint and result format.  The original v1 endpoints will be sunset/deprecated within months so this connector should move to the new V2 version.

### Describe the solution you'd like

Move the connector to use the /v2/ endpoint instead of the /v1/. Specific behavior changes are summarized here: https://docs.snowflake.com/en/release-notes/2021-11-bcr.html#changed-and-deprecated-functionality.

Full API documentation is here:
https://docs.snowflake.com/en/developer-guide/sql-api/guide.html

### Describe alternatives you've considered

The v1 will be sunset, so for the API to continue to work, the move is required to keep using the SQL API instead of driver.

### Additional context

N/A

**Comment by natalie-pienkowska** [comment]
Thanks for the feedback @sfc-gh-ngoodman! We are actively working on this and are planning to have the update late April, so I will be closing this bug :)

**Comment by sfc-gh-pmaric** [comment]
@natalie-pienkowska  has this been completed?  Any update on timeline would be appreciated.  Thank you.

**Comment by natalie-pienkowska** [comment]
We are targeting early July.
