### ISSUE TITLE
Facebook connector - 404

### ISSUE THREAD

**Issue by Gregghis** [microsoft/PowerPlatformConnectors#162]
Hi,

I try to deploy the facebook sample custom connector with no success.

- I registered a facebook app, with product "Facebook login" and I marked it as "native app".
- On the apiProperty.json file I updated the clientID.
- with the paconn I registered the connector on my tenant using the commands 
paconn login
paconn create -s [Path to settings.json] --secret [The OAuth2 client secret for the connector]

No error shows untill this point, but accessing the custom connector I the 404 page with this message
"Error: Failed to retrieve api with http status code 'ApiResourceNotFound' and error message 'Could not find api ..."

Any suggestions will be appreciated
Thanks

**Comment by mamurshe** [comment]
Thanks for the report. Please review the recent API changes for Facebook and update the connector to fit you need.
