### ISSUE TITLE
[BUG] Star wars connector Page is wrong case for all "Get all" requests

### ISSUE THREAD

**Issue by Intellemerc** [microsoft/PowerPlatformConnectors#1624]
### Type of Connector

Independent Publisher Connector

### Name of Connector

Star Wars

### Describe the bug

It looks like the star wars flow connector uses Page(uppercase P) as a query parameter but, API expects it to be lowercase page and urls are case sensitive

For Example:
https://github.com/microsoft/PowerPlatformConnectors/blob/1add4c2e55b3f09acac51ba53d0c948baa91d9ab/independent-publisher-connectors/Star%20Wars/apiDefinition.swagger.json#L272

This would be for all the parameters that accept page, People, Species, Planets, and Films

### Is this a security bug?

No, this is not a security bug

### What is the severity of this bug?

Severity 3 - Minor issue

### To Reproduce

Create flow that grabs page 1 and page 2 of the any of the "Get All" endpoints(People, Species, Planets, or Films)

Both results are identical, it is not changing the page

You can see it in the "next page" url, it has both cases in the url(the Uppercase 
https://swapi.dev/api/people/?Page=5&page=1

### Expected behavior

Use lowercase page, this is the only one supported by the endpoint

### Environment summary

Production Power Automate workspace

### Additional context

None

**Comment by last72** [comment]
@Intellemerc Thanks for your contibution in this repository. I have replaced uppercase with lower case P. I haven't tested swagger file but you can see change I made here #1628

**Comment by natalie-pienkowska** [comment]
Thank you @Intellemerc for reporting this issue and @last72 for quickly taking a look and submitting a fix! :)
