### ISSUE TITLE
Missing redirect URL in application registration.

### ISSUE THREAD

**Issue by parclarke** [microsoft/PowerPlatformConnectors#1733]
Hi when I try to sign in using a Flow I get the following error: Missing redirect URL in application registration.
I have verified that the following Redirect URL https://global.consent.azure-apim.net/redirect is in our ServiceNow application registry. 
Am I supposed to use a Flow Url instead?

**Comment by parclarke** [comment]
There was a typo in the application registry but now I'm getting the following error: 
Server Error in '/' Application.
The length of the query string for this request exceeds the configured maxQueryStringLength value.

**Comment by natalie-pienkowska** [comment]
Hi @parclarke! Thanks for submitting this issue. It looks like this issue has to do with the existing connector ServiceNow. Please submit your question to the forum to get help:  https://powerusers.microsoft.com/t5/Using-Connectors/bd-p/ConnectingToData
