### ISSUE TITLE
Some checks were not successful while updating Independent Publisher Connector

### ISSUE THREAD

**Issue by sekharmalla** [microsoft/PowerPlatformConnectors#1849]
Hello Dear Team,

I hope you all are doing great :)

This weekend I have updated a few Notion Actions and was trying to commit for verification however I am facing an error as Some `checks were not successful` i will add the failed link below. 

https://github.com/microsoft/PowerPlatformConnectors/commit/6c4fe550d69466a4a97200b6b5fb8f8b07937f32

only thing i have updated is the swagger definition and Readme file and it's failing at checks,

I hope someone can help me soon

Thanks 
Have a great day :)

**Comment by troystaylor** [comment]
I've noticed you've introduced a number of blank titles and default response schemas. I would start by fixing those. If you are still getting validation errors, please paste them here and I'll take a look.

**Comment by sekharmalla** [comment]
Hi @troystaylor,

Thank you for your response,

I think there is a misunderstanding because I have got `apiDefinition.swagger.json validated successfully.` message in CLI

there is something that happened during pushing it to my dev branch. it went as commit to this repository.



<img width="1374" alt="image" src="https://user-images.githubusercontent.com/43902003/182146722-18657aac-8404-4ddf-9cd1-8d725e741750.png">


do let me know if you have any questions 

Thanks,

**Comment by sekharmalla** [comment]
alright Thanks @troystaylor,

As you said i did undo my commit however, to merge! one of my (SHRTCODE) https://github.com/microsoft/PowerPlatformConnectors/pull/1792 connector is still in deployment that said i am not able to merge, 

also thanks for the tip about creating new branch in my fork and commit changes to it, as you suggested i have created a new branch under dev called `Notion` and pushed New `Notion (Indemendent Publisher Connector) ` changes to update the connector and i am here right now, is this okay i can merge ? Please advise me


<img width="1374" alt="image" src="https://user-images.githubusercontent.com/43902003/182163636-c5710a49-aaea-48f9-9dea-f7fc84b8b8de.png">


Thanks,

**Comment by troystaylor** [comment]
As long as that branch has just the files for Notion, you should be good to create the PR.

**Comment by sekharmalla** [comment]
Right, @troystaylor

I have checked and their only Notion files only update remaining files and folders are the same as Dev but after opening new PR it's failed and have these error,

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/43902003/182175987-da6440ab-6d92-47e0-96bc-24f6900b2965.png">

can you tell me what went wrong?

Thanks

**Comment by troystaylor** [comment]
Those breaking changes will need to be confirmed by the connector team, which now that you've opened the PR, they'll be able to communicate that with you. You should hear from them in the next 24-48 hours.

**Comment by sekharmalla** [comment]
Thank you very much @troystaylor for all your help, 

I really appreciate it.

Thanks, I am closing this issue now. 👍🏼
