### ISSUE TITLE
DadJokesIO (Independent Publisher) issue

### ISSUE THREAD

**Issue by asrvstv5** [microsoft/PowerPlatformConnectors#1880]
Api Name - shared_dadjokesioip

Bug description - not enough dad jokes

Is this a security bug? (Y/N)

What is the severity of this bug?

**Comment by troystaylor** [comment]
Hi Amitesh,
This isn't a bug. My connector for this service includes all 18175 jokes available through the service.
Thanks,
Troy

CC: @natalie-pienkowska, please close.

**Comment by asrvstv5** [comment]
Hi, My bad. I did not mean to spam. Was testing the issue submission feature at that time. I forgot to delete and/or close the issue. Will do so now
