### ISSUE TITLE
[BUG] 403 response using 'Update an adaptive card in a chat or channel'

### ISSUE THREAD

**Issue by Narizz28** [microsoft/PowerPlatformConnectors#1887]
### Type of Connector

Certified Connector

### Name of Connector

Update an adaptive card in a chat or channel

### Describe the bug

Always get the error:
The ID of the user attempting to edit the message, ID:<my_user_id_here> does not match the actual user ID of the original sender, ID:

There is nothing after the Second ID in the error, like it doesn't know what the FlowBot ID from the original Card post is.

### Is this a security bug?

No, this is not a security bug

### What is the severity of this bug?

Severity 1 - Connector is broken or there's a very serious issue

### To Reproduce

Add Post_adaptive_card_and_wait_for_a_response to flow
Add Update_an_adaptive_card_in_a_chat_or_channel to flow.
Use Post card message ID in the Update action
Match all other setting from Post action, changing the contents of the adaptive card in the Update.
![image](https://user-images.githubusercontent.com/72027960/184544008-33e4878c-66b6-45d5-893a-c56e3db24fa3.png)

My result is always:  
The ID of the user attempting to edit the message, ID:<my_user_id_here> does not match the actual user ID of the original sender, ID:

### Expected behavior

New Adaptive card to take the place of the Update Message from the Post action 

### Environment summary

make.powerautomate.com editor via Chrome/Edge
Power Automate App in MS Teams on Windows 10.

### Additional context

2 other reporters in Community Forums: https://powerusers.microsoft.com/t5/Building-Flows/Update-an-Adaptive-card-in-a-chat-or-channel-works-only/m-p/1695210#M187923

**Comment by Narizz28** [comment]
Seems to actually be a bug in the "Post adaptive card and wait for a response" action not setting the sending user ID.

**Comment by truespinmice** [comment]
The same scenario and the same error on my end: "_update adaptive card The ID xxxxxxxxxxxxxxx of the user attempting to edit the message, ID does not match the actual user ID of the original sender_".
The only difference is that I'm using Logic Apps not Power Automate. But I tested it using PA also and the result was exactly the same.

It's causing real issues with our business processes so I hope MS will fix it very soon...

**Comment by truespinmice** [comment]
Got an update from Microsoft:
_It's a known issue at MS side as well and our senior team is working on it.
Last update on internal ticket with engineering team states changes may take 3-4weeks time.
Updated on - 2022-09-07 00:34:30 IST_

So hopefully in the next 3-4 weeks it will be fixed. Will keep you posted.

**Comment by waterskijubilant** [comment]
I just tested this and it's working as expected now!

**Comment by Narizz28** [comment]
@waterskijubilant What exact actions did you test? I just tried again and I'm still getting the same error. "Post_adaptive_card_and_wait_for_a_response" -> Submit Button (Action.Submit) pressed -> "Update_an_adaptive_card_in_a_chat_or_channel" is what I'm testing. The "Update an adaptive card..." is the action that fails with the 403 "The ID of the user attempting to edit the message, ID:<my_user_id_here> does not match the actual user ID of the original sender, ID:"

**Comment by waterskijubilant** [comment]
@Narizz28 
I used the "Post adaptive card and wait for a response" action then the "Update an adaptive card in a chat or channel" action to update the card.

I was trying to do this Friday and I was getting the same error as you, but I tried it again today and it's working now.

Here is a screenshot of what I have set up.

![Screenshot 2022-09-19 150527](https://user-images.githubusercontent.com/89154722/191095765-3e5e3721-ad17-4591-a65e-8246c856304e.png)

**Comment by Narizz28** [comment]
I too just got it to work, but I had to create new flow.

**Comment by BongoEADGC6** [comment]
Just adding some info. Using "Save as", nor replacing the action with the same action within a flow, does not fix this issue.

**Comment by Narizz28** [comment]
Good Context @BongoEADGC6. I think that's why my original wflow didn't work, but the new one I created did.

**Comment by truespinmice** [comment]
Thanks for the update guys. Unfortunately it doesn't work on my end. Did the same test as you all -> I've created a new flow with 2 actions only (Post adaptive card and wait for a response + Update an adaptive card in a chat or channel) but got the same error.

What regions are you in (O365/Power Platform)? I'm in the UK (O365 tenant). 
Dataverse version: 9.2.22084.00190
2022 release wave 2: OFF

![image](https://user-images.githubusercontent.com/20261357/191189251-da17bd25-3227-4fb0-90ad-db7ccee2272a.png)
![image](https://user-images.githubusercontent.com/20261357/191189347-40e8afda-7c7a-430f-ba41-496c7a0ef206.png)

**Comment by truespinmice** [comment]
also, I didn't get any update on my ticket in Microsoft (it is still open) so I'm considering this as not resolved...

**Comment by BongoEADGC6** [comment]
This still does not work for me either. Maybe it's changed for certain customers and is making it's way around.

**Comment by Tim-Roe** [comment]
Strangle I got the same error even after building a new logic app with the same two actions.
But when I did a test using power automate/flow it did work with the two actions.

**Comment by truespinmice** [comment]
OMG! It's finally working on my end! Tested on 2 different tenant (but in the same region).
Also last night got update from MS:
_As discussed on call, I informed you that this is a know issue and it will be resolved by our engineering team who is working on it. I would like to update you that the fix was rolled out on 16th Sept 2022, and it may have already been deployed to your region, otherwise it should hopefully replicate next week or the week after at the latest.
You may check the status from your end and let us now if its still same or if it’s started working.
Appreciate your time and patience._

@Tim-Roe will test it on Logic Apps too and will let you know (as this is my case too).

**Comment by truespinmice** [comment]
@Tim-Roe , confirmed with Logic Apps too!
@Narizz28 I think you can close/solve this bug.

**Comment by Tim-Roe** [comment]
> @Tim-Roe , confirmed with Logic Apps too!

Yes, confirmed working in both platforms for me now too.

**Comment by Narizz28** [comment]
> I'm experiencing this issue

Try building the flow scratch or remove and re-add the actions in your flow. That's what a lot of people had to do, as "something" may have been left over in the actions from before the fix.
