### ISSUE TITLE
Strava (Independent Publisher) issue

### ISSUE THREAD

**Issue by jtaki** [microsoft/PowerPlatformConnectors#1957]
Api Name - shared_stravaip

Bug description -
Can't authenticate with Strava through connector. Returns bad request for redirect URI
`{
"message": "Bad Request",
"errors": [
{
"resource": "Application",
"field": "redirect_uri",
"code": "invalid"
}
]
}`

Is this a security bug? (Y/N)
N

What is the severity of this bug?
2. Major feature prohibiting use of connector.

**Comment by troystaylor** [comment]
@RichardWie - are you able to assist with this?

**Comment by RichardWie** [comment]
You will need an CLIENTID (can't submit the connector with my key).
I'm not sure what the best way is for adding it, but it should be added to the apiProperties.JSON file
