### ISSUE TITLE
Rename paconn settings.json file to something less generic

### ISSUE THREAD

**Issue by joem-msft** [microsoft/PowerPlatformConnectors#198]
**Is your feature request related to a problem? Please describe.**
settings.json is too generic a name for tooling. e.g. /.vscode/settings.json. This file is owned by vscode, but because it's in a subfolder it's unambiguous.

Furthermore, writing VS Code tooling to this file would be simpler if it had a unique name.

Also, we can add a more specific filename to our `.gitignore` to prevent this file (a user-specific) file from accidentally being added to the repo.

**Describe the solution you'd like**
how about `paconn-settings.json`?
all lowercase and usage of '-' allows for easy normalization of the filename.

**Comment by natalie-pienkowska** [comment]
Thank you for your feedback. We have decided not to move forward with the suggestion.
