### ISSUE TITLE
paconn and PR validation should not save clientId values, and ensure they aren't added in PRs

### ISSUE THREAD

**Issue by joem-msft** [microsoft/PowerPlatformConnectors#201]
We should:
1) ensure paconn doesn't automatically save clientIds
2) PR process should validate that clientIds are not checked into the repo.
3) paconn tool should be designed to allow a developer to provide the clientId (it already provides the clientSecret as a parameter).

_Originally posted by @mamurshe in https://github.com/microsoft/PowerPlatformConnectors/pull/199_

**Comment by natalie-pienkowska** [comment]
We have added this issue to the backlog and will prioritize accordingly. Thanks again for adding this issue @joem-msft :)
