### ISSUE TITLE
Veteran Confirmation (Independent Publisher) issue

### ISSUE THREAD

**Issue by EdGCRM** [microsoft/PowerPlatformConnectors#2157]
Api Name - shared_veteransaffairsip

Bug description - Documentation Link Inop for both MS and Git

Is this a security bug? (Y/N) N

What is the severity of this bug? Keeps me from using the connector :(

**Comment by troystaylor** [comment]
Hi Ed,
For the Independent Publisher connector, you will need to register for [production access.](https://developer.va.gov/onboarding/request-prod-access) I now realize this after submitting the connector as part of M365 Chicago. You can also download the Swagger from my [repo](https://github.com/troystaylor/PowerPlatformConnectors/blob/VA/independent-publisher-connectors/Veterans%20Affairs/apiDefinition.swagger.json) and change the host to the sandbox, sandbox-api.va.gov, to test the service.
