### ISSUE TITLE
Support client credentials Oauth 2.0 flow

### ISSUE THREAD

**Issue by mlainez** [microsoft/PowerPlatformConnectors#225]
At the moment, it seems that only the accessCode flow is supported in the generic Oauth 2.0 identity provider. However, our APIs use the authorization code flow and client credentials flow. Which makes an integration with Microsoft Power Automate impossible for us unless we change our Oauth 2.0 implementation.

When I try to create a custom connector forcing the client credentials flow using the "application" as flow. It gets uploaded with the CLI but then when I try to make a connection with my connector, it fails saying it is missing an "authorizationUrl", which makes me think it falls back to accessCode all the time.

Custom connectors should ideally be allowed to chose at least the client credentials flow and not just the accessCode flow.

**Comment by hajekj** [comment]
In fact some first party connectors already have the ability to use client_credentials, so it would be great to have the ability too. We also have many use cases for this.

**Comment by mlainez** [comment]
@mamurshe any update on this issue? I noticed it was marked as bug, let me know if you need any help testing it.

**Comment by nk-gears** [comment]
Atleast temporary workaround to increase the timeout in desktop client will be useful. Its very hard to develop as the token expires very soon.

**Comment by natalie-pienkowska** [comment]
Hi @mlainez this is very similar to this issue: https://github.com/microsoft/PowerPlatformConnectors/issues/287. We have added it to the backlog and will prioritize accordingly.

**Comment by hajekj** [comment]
@natalie-pienkowska this one is unrelated to #287.

This (#225) issue is asking for official guidance on enabling client_credentials flow with custom connectors like some first party connectors have (eg. Connect with service principal):
![image](https://user-images.githubusercontent.com/8337913/145972505-a1fd53e7-c507-4b7f-a77b-3da0ee393c10.png)

The other (#287) issue is asking for support to call the Power Automate API with client_credentials flow which is needed to be able to handle Power Automate operations non-interactively.

Please re-open this issue.

**Comment by hajekj** [comment]
This is now on roadmap for Release Wave 1 2022: https://docs.microsoft.com/en-us/power-platform-release-plan/2022wave1/power-platform-pro-development/service-principal-support-connectors

**Comment by jeremyp557** [comment]
I can't see the feature in 2022wave1????

**Comment by jeromekol** [comment]
Are there any updates on this topic?

**Comment by 1trevor** [comment]
Is there any updated on this? It still doesn't appear to be possible to use service principals / client credentials flow with custom connectors.

**Comment by hajekj** [comment]
Yes, this is not in preview - https://powerapps.microsoft.com/en-us/blog/public-preview-of-new-custom-connector-enhancements/
