### ISSUE TITLE
Connection Failure -  Insufficient scopes

### ISSUE THREAD

**Issue by rhinoroo** [microsoft/PowerPlatformConnectors#2302]
Using Power Automate to try and establish a connection to a HubSpot developer account and application.
I receive the following error when authenticating:
Couldn’t complete the connection
Insufficient scopes were provided. Please contact the app developer.

**Comment by troystaylor** [comment]
You need to enable the following scopes in your HubSpot app:

crm.objects.contacts.read tickets crm.objects.marketing_events.read content reports actions timeline oauth forms files crm.objects.marketing_events.write crm.schemas.custom.read crm.objects.custom.read crm.objects.feedback_submissions.read crm.objects.custom.write

**Comment by rhinoroo** [comment]
Got it, thank you for the incredible fast response!
