### ISSUE TITLE
You Need A Budget (Independent Publisher) issue

### ISSUE THREAD

**Issue by vansummeren** [microsoft/PowerPlatformConnectors#2320]
Api Name - shared_youneedabudgetip

Bug description

I cannot find the connector when I try to create a new flow.
In the connectors overview I see the connector, I have a premium environment (pay as you go through an azure subscription)
I am able to select other premium connectors, but the you need a budget one is simply not showing up.

Is this a security bug? (Y/N) No

What is the severity of this bug?

**Comment by troystaylor** [comment]
Which region are you connecting to?

**Comment by vansummeren** [comment]
Wow, that was fast!
I'm trying to connect to Switzerland.

**Comment by troystaylor** [comment]
@Amjed-Ayoub can you confirm that this connector is available in the Switzerland region?

**Comment by vansummeren** [comment]
In the documentation it says the following about availability:

Power Automate	Premium	All [Power Automate regions](https://learn.microsoft.com/en-us/flow/regions-overview) except the following:
     -   US Government (GCC)
     -   US Government (GCC High)
     -   China Cloud operated by 21Vianet
     -   US Department of Defense (DoD)
   
I am trying with a new environment in Europe now.

**Comment by vansummeren** [comment]
When I use an environment in Europe, I can see the connector as I would expect.
It seems that it's not deployed to Switzerland and the documentation is outdated.

**Comment by troystaylor** [comment]
Adding @jopanchal - is there a known region restriction for Switzerland?

**Comment by Amjed-Ayoub** [comment]
Hello @vansummeren and @troystaylor,

I hope you are doing well.

In our **deployment** we don't have a specific region for Switzerland, but we include it within Europe deployment.
I can confirm that the connector is deployed in Europe region in Power Automate(Includes Switzerland region), please see below.
![image](https://user-images.githubusercontent.com/97551789/214395625-8607af09-fa3b-480a-96d4-efb97a648a59.png)

And in Switzerland region in Logic Apps as well. Please see below.
![image](https://user-images.githubusercontent.com/97551789/214396039-70bac18a-cf16-49f1-8309-6f99cb955475.png)


Thank you so much.

Best regards,
Amjed Ayoub
