### ISSUE TITLE
paconn validate (InvalidAuthenticationToken)

### ISSUE THREAD

**Issue by vjdpk2206** [microsoft/PowerPlatformConnectors#2399]
Describe the bug:
When attempting to validate a connector you get the below error
![Screenshot 2023-02-17 122647](https://user-images.githubusercontent.com/125638177/219571742-626ae466-193c-4d23-9a46-426c3fac0e38.png)
Navigating to the URL given in the error

https://api.powerapps.com/providers/Microsoft.PowerApps/objectIds/139a6b45-42e4-4248-9034-1e71237f0eca/validateApiSwagger?api-version=2016-11-01&enableConnectorCertificationRules=true

returns

{"error":{"code":"MissingAuthorizationHeaderAndClientCertificate","message":"A client certificate or authorization header was not provided."}}

To Reproduce
paconn validate --api-def apiDefinition.swagger.json
I followed the instructions in this article: https://learn.microsoft.com/en-us/connectors/custom-connectors/paconn-cli#api-properties-file

Expected behavior

**Comment by Amjed-Ayoub** [comment]
Dear @vjdpk2206,

Thank you so much for reaching out.

We are aware of this issue as it is affecting a lot of our partners. Rest assured that we are doing our best to resolve this in a timely manner. 
Please accept our apologies for any inconvenience this may cause.

Thank you so much again for your patience and understanding.

Best regards,
Amjed Ayoub

**Comment by vjdpk2206** [comment]
Hi @Amjed-Ayoub 

I'm currently in the certification process for my connector, which requires me to validate my apiProperties and apiDefenition files using the paconn CLI. Since I'm experiencing this issues, I'm wondering if there are alternative methods for validating my connector files, or if it's possible to submit them without validation.

**Comment by troystaylor** [comment]
You could add the connector to a solution and use the pac CLI. I believe that method is still working.

**Comment by RedsGT** [comment]
Temp Fix:
https://github.com/microsoft/PowerPlatformConnectors/issues/2400#issuecomment-1436040869

**Comment by mamurshe** [comment]
A fix with correct resource id is published in pypi. To update to 0.0.21 run `pip install paconn -U`

This prod version with `0.0.x` version number uses ADAL authentication library and may not work for all cases. A new version with MSAL authentication library, version number 0.1.x, is in development and can be installed from test pypi using `pip install --index-url https://test.pypi.org/simple paconn -U`
