### ISSUE TITLE
Add Canvas App Export Feature

### ISSUE THREAD

**Issue by starwarskidfan** [microsoft/PowerPlatformConnectors#26]
I would really like the ability to export apps pragmatically and move then to different environments. I feel like most people, that are using PowerApps as fast deployed solutions, have a Dev Environment and a Prod Environment. 

If you could export the app and then import the app in a new environment I feel like this would solve the problem.

You also could just add functionality to copy it to a different environment, but it might be easier/more flexible to just allow exporting and importing apps

**Additional context**
https://docs.microsoft.com/en-us/power-platform/admin/environment-and-tenant-migration

**Comment by jatin085** [comment]
The request should be made in PowerApps Community forum. Please feel free to open up a discussion at https://powerusers.microsoft.com/t5/General-Discussion/bd-p/PowerAppsForum1.

**Comment by JatinSanghvi** [comment]
The request should be made in PowerApps Community Forum. Please feel free to open up a discussion at https://powerusers.microsoft.com/t5/General-Discussion/bd-p/PowerAppsForum1.
