### ISSUE TITLE
[paconn] Add support for logout

### ISSUE THREAD

**Issue by schabungbam** [microsoft/PowerPlatformConnectors#264]
Problem:
Sometimes we use a different accounts to deploy a connector across different environments (a PROD/TEST environment vs a community environment). The paconn utility, once logged in, cannot be used to target the other environment. The only option seems to wait out until the token expires - which is extremely painful.

**Describe the solution you'd like**
Add a paconn logout command.

**Describe alternatives you've considered**
Another window/session.

**Comment by mamurshe** [comment]
`paconn login -f` will force a login to a different account.

**Comment by dougelliott** [comment]
Logout command for paconn has been added in https://github.com/microsoft/PowerPlatformConnectors/pull/290 for version 0.0.14

This new functionality can be used via `paconn logout`

Closing issue since feature request was implemented.
