### ISSUE TITLE
[paconn] Paconn Update Throws Error

### ISSUE THREAD

**Issue by nk-gears** [microsoft/PowerPlatformConnectors#267]
**Describe the bug**
Recently (in the last 3 days) i am getting a weird error when trying to update the connectors via paconn-cli. Issue exists on both Mac OS and Linux Platform

```
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/projects/.venv/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/projects/.venv/lib/python3.6/site-packages/knack/invocation.py", line 188, in execute
    cmd_result = parsed_args.func(params)

  File "/projects/freelancing/azure-app/azure-fn-msflow-agent/plangrid-agent/swagger/fp/shared_plangrid-20-5fa1c41dcf6720de46-5f986c0f1bdfc46983/.venv/lib/python3.6/site-packages/paconn/apimanager/apimanager.py", line 115, in request
    response_content = json.loads(response.content)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**To Reproduce**
Download any Connector using Paconn download and just try to update back using paconn update -s settings.json

**Expected behavior**

**Environment summary**
Installed using pip install

**On Linux**
paconn --version
0.0.13

Python (Linux) 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0]

**On Mac**
0.0.13

Python (Darwin) 3.7.7 (default, Mar 21 2020, 14:41:45)
[Clang 9.0.0 (clang-900.0.39.2)]

**Additional context**

**Comment by nk-gears** [comment]
I had a suspect that this happens due to a network latency. Then i created a VM in US Region and installed paconn and tried. To my surprise the same connector.json worked in just 20 seconds.

So, you need to check how to deal with the network latency due to geographical usage. I reside in India and i am decided not to use PACONN from my  terminal anymore.

**Comment by maventis** [comment]
I have exactly the same issue and I agree with you @nk-gears, it seems to be latency-based as I tried the same as you except with a proxy instead, and it worked fine within 20 seconds.

**Comment by mmurshed** [comment]
Hi,
I think I have some idea about the problem. I think the rest call is returning with an empty response due to latency most likely. The CLI is trying to parse the empty response and fails with JSON error. The resolution would be to not parse empty response and output to console saying that it encountered and empty response.

Since latency isn't an issue for me I can't reproduce. Would any of you be willing to help me test this fix? @maventis @nk-gears

**Comment by nk-gears** [comment]
@mmurshed I started using a VPN (TunnelBear) and then run the paconn update. Now  i no more have this error as the latency issue is resolved.

I can definitely test and send you the results related to the empty JSON fix. But that doesn't solves the actual problem which the users are facing on other side of the globe.

What i recommend is, when uploading the changes to the server via update, it will be great if you use some compression techniques while POSTing them to the PACONN server. This way we will have a huge benefit for users who have 400+ operations in a single swagger file.

**Comment by nk-gears** [comment]
@mmurshed Closing this as i am using VPN to paconn update to resolve latency.
