### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by usuarrio-id81214293** [microsoft/PowerPlatformConnectors#2758]
[]()yo taiger

**Comment by abdsimpore086** [comment]
Comment retirer mais fond s'il vous plaît

**Comment by abdsimpore086** [comment]
![Screenshot_20231116-211453](https://github.com/microsoft/PowerPlatformConnectors/assets/135830421/c90d3a86-f611-4f60-86f7-d166fe6b7f42)
