### ISSUE TITLE
[BUG] @connectionParameter expression not resolved

### ISSUE THREAD

**Issue by fordosa90** [microsoft/PowerPlatformConnectors#2906]
### Type of Connector

Independent Publisher Connector

### Name of Connector

Sapling AI

### Describe the bug

See pull request for reference: https://github.com/microsoft/PowerPlatformConnectors/pull/2661

The underlying service uses special authentication through the body of every single request:
**POST** {endpoint_url}
_{
  key: {api_key},
  data: ...
}_
Example actual endpoint: https://sapling.ai/docs/api/autocomplete

Natively, the supported custom connector authentication types don't allow this, however, based on documentation it should be still possible to achieve, using combination of:
  - Set-Property policy template
  - @connectionParameter expression

When trying to use this way - see again referenced PR comment thread - somehow it seems, that the expression does not get resolved by the platform (Microsoft). I have had additionally email chain with the product team since June 2023, from which the thread has been closed by redirecting to Microsoft Support. After raising a ticket with Microsoft support, they have redirected me towards this github issue tracker.

### Is this a security bug?

No, this is not a security bug

### What is the severity of this bug?

Severity 1 - Connector is broken or there's a very serious issue

### To Reproduce

1. Create new custom connector, can be against dummy service, or test service, such as https://webhook.site
2. Set up no authentication by the wizzard
3. Add a random action, does not matter, what, but make it POST request
4. Save connector
5. Add manually a new connectionParameter to the apiProperties called "api_key" (easiest way I assume is through CLI)
6. Define Set-Property policy template, to set within @body the "key" property to equal the connection parameter
7. Test the connector

https://learn.microsoft.com/en-us/connectors/custom-connectors/policy-templates/expressions/expressions
https://learn.microsoft.com/en-us/connectors/custom-connectors/policy-templates/setproperty/setproperty

You can see, that the platform does not resolve the expression, rather treats it as a string and simply forwards to the endpoint within the body of the POST message meaning that the policy template works, however the expression does not seem to be supported.

### Expected behavior

https://learn.microsoft.com/en-us/connectors/custom-connectors/policy-templates/expressions/expressions
https://learn.microsoft.com/en-us/connectors/custom-connectors/policy-templates/setproperty/setproperty

Expected behavior is, that the connectionParameter expression within the POST body (placed there correctly by the Set-Property template) gets resolved to the actual value of the connection parameter.

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build)
CLI version (paconn --version)
OS version
Shell Type (e.g. bash, cmd.exe, Bash on Windows)

Native latest version of power platform (PowerAutomate flow), custom connectors

### Additional context

Issue raised in many streams even with product team, has been thrown around without ownership

**Comment by troystaylor** [comment]
@fordosa90 Hi Andras, I'm going to reply here as I have found a workaround, but even with extensive testing your found bug still exists with the policy template.
Since the property template isn't working, I instead used the query template to set the connectionParameter to a query parameter. Then I created this custom code to move the query parameter to the body and send the request:

```
using Newtonsoft.Json;
using System.Collections.Generic;

public class Script : ScriptBase
{
    public override async Task<HttpResponseMessage> ExecuteAsync()
    {
        var request = this.Context.Request;
        var query = new Uri(request.RequestUri.AbsoluteUri).Query;
        var queryParams = HttpUtility.ParseQueryString(query);
        var key = queryParams["key"];

        var requestBody = await request.Content.ReadAsStringAsync();
        var requestBodyDictionary = JsonConvert.DeserializeObject<Dictionary<string, string>>(requestBody);

        var jsonObject = new Dictionary<string, string>
        {
            { "key", key }
        };

        foreach (var kvp in requestBodyDictionary)
        {
            jsonObject[kvp.Key] = kvp.Value;
        }

        var json = JsonConvert.SerializeObject(jsonObject);
        var uriBuilder = new UriBuilder(request.RequestUri);
        var queryParameters = HttpUtility.ParseQueryString(uriBuilder.Query);
        queryParameters.Remove("key");
        uriBuilder.Query = queryParameters.ToString();
        var modifiedUri = uriBuilder.Uri;

        var modifiedRequest = new HttpRequestMessage(request.Method, modifiedUri)
        {
            Content = new StringContent(json, Encoding.UTF8, request.Content.Headers.ContentType.MediaType)
        };

        var response = await this.Context.SendAsync(modifiedRequest, this.CancellationToken).ConfigureAwait(false);
        return response;
    }
}
```

![brave_xhSgsP5NQL](https://github.com/microsoft/PowerPlatformConnectors/assets/44444967/19fa5da2-5203-4c8b-aa72-0ea341998ff6)

Please reach out to me if you would like to collaborate further on the Sapling connector.

CC: @vmanoharas @jopanchal

**Comment by fordosa90** [comment]
@troystaylor I greatly appreciate the effort and the identified workaround!

I still have also my other, orignal workaround without using code (easier maintenance):
  - create an input parameter
  - default the parameter to the connectionParam (api key)
  - hide the parameter by marking it as internal

That said, I still would like to receive any kind of offical answer from MSFT (through the internal email channel, through the opened ticket, or even through here in this issue @jopanchal @vmanoharas ) for the official supported path (expression together with Set-Property policy template) as the preferred way would be doing things properly without workarounds

**Comment by fordosa90** [comment]
@troystaylor again, appreciate greatly the input, the final solution became similar, just building on top of native authentication (API header) instead of policy templates.

Hard to plan with future supportability not knowing the feature plans (if or when body type authentication becomes a possibility, would it be better to replace a policy template or the security tab auth method) but custom code executes quicker with the header replacements instead of query parameters and it is less code to maintain.
