### ISSUE TITLE
Persist login with token or similar

### ISSUE THREAD

**Issue by tom-sherman** [microsoft/PowerPlatformConnectors#30]
I'm asked to login very frequently, which disrupts the development flow of the custom connector. Is it possible to specify something like an OAuth token so that I am persistently logged in?

This would also enable CI/CD of connectors.

**Comment by schabungbam** [comment]
Not sure - is this for the CLI tool?
Or, your connection is getting expired?  Ideally, we should be refreshing the token automatically.

**Comment by tom-sherman** [comment]
@schabungbam Yes i'm talking about the `paconn` CLI tool, it asks me to login I think every hour.

**Comment by schabungbam** [comment]
@mamurshe - Any idea if there is a way to fix this? Or are there other solutions?

**Comment by mamurshe** [comment]
Hi @tom-sherman ,
Thanks for bringing up the issue. As we are working to include the CLI in our own CI/CD, I am working to enable support for Azure Active Directory. I will escalate this effort and work on publish it sooner.

**Comment by gpsarkar** [comment]
@mamurshe Is there any ETA for this implementation or workaround to use this in cicd process?

**Comment by mamurshe** [comment]
Hi,
Unfortunately no ETA yet. But we have this request in our backlog.

**Comment by mamurshe** [comment]
I would encourage to implement the feature. Please let me know if I can help in any way. I will close this issue for now.

**Comment by tom-sherman** [comment]
@mamurshe I would strongly suggest that this issue is kept open until the actual feature is resolved so that others can locate it and potentially start working on a solution
