### ISSUE TITLE
Validate function does not recognize allowable number formats such as int64

### ISSUE THREAD

**Issue by eshupps** [microsoft/PowerPlatformConnectors#312]
**Describe the bug**
If the api definition file contains definition with properties of type "number", with format "int64", the validation function throws the following error: 

_The type/format 'number/int64' is not recognized._

This is inconsistent with the OpenAPI 2.0 specification, which, in addition to an empty value, allows the following format values for type "number":

float
double
int32
int64

**To Reproduce**
Create a definition similar to the following:

"customDefinition" : {
      "type" : "object",
      "properties" : {
        "prop1" : {
          "type" : "number",
          "format" : "int64",
          "description" : "Property 1"
        }
}

Run paconn validate --api-def apiDefinition.swagger.json

Command returns "definitions/customDefinition/properties/prop1/format: The type/format 'number/int64' is not recognized".

**Expected behavior**
The definition should pass validation.

**Environment summary**
Install Method: pip
CLI Version: 0.0.14 (Python 3.8.3)
OS: Mac OS 10.15.5

**Comment by natalie-pienkowska** [comment]
@eshupps Do you mind reverifying this issue with the latest version of paconn? This will help us decide on next steps :)
