### ISSUE TITLE
Update readme.md with instructions for merging and submitting PR's

### ISSUE THREAD

**Issue by eshupps** [microsoft/PowerPlatformConnectors#355]
The instructions for submitting a connector to the repo terminate at getting the local dev environment configured. There are no steps provided for how to proceed beyond copying connector artifacts into a subdirectory. This is confusing for people who do not use Git on a regular basis. A generic statements such as "Updates to certified connectors must first be made through a pull request to the dev branch for review by the connector owner" does not provide enough information to complete the process. 

Since final certification and deployment is dependent on this task, it is imperative that clear instructions be given on how to properly merge a dev branch and submit a PR to maximize the possibility of acceptance. As with the previous section on creating a fork, the certified connectors section should provide sample commands and sequential steps. There are too many ways to accomplish a task in Git to leave it at generic, open-ended statements.

**Comment by mamurshe** [comment]
@eshupps you can submit a section on the documentation since it's open source. Git is a process that is well documented and out of scope for certification. Please feel free to submit a section that you think will be helpful.
