### ISSUE TITLE
Have I Been Pwned (Independent Publisher) issue

### ISSUE THREAD

**Issue by stevenmaske** [microsoft/PowerPlatformConnectors#3688]
Api Name - shared_haveibeenpwnedip

Bug description - The last update for the connector was 1/13/2022 and not all calls from v3 are supported.  

See: https://haveibeenpwned.com/api/v3

I wanted to inquire if the publisher has any plans to update the connector before I attempt to recreate it using the v3 documentation.  Thanks.

Is this a security bug? - No

What is the severity of this bug? - Limited functionality

**Comment by troystaylor** [comment]
Hi Steven,
I am the publisher of the connector. I did not know there was a new API version, and I will work to update the connector.

Troy

**Comment by stevenmaske** [comment]
Hi @troystaylor, I was just curious if you had an estimate on updating this connector?   No pressure, I just want to set a reasonable expectation for myself on when to check back.  Thanks.

**Comment by troystaylor** [comment]
@stevenmaske The update should be submitted in the next two weeks

**Comment by troystaylor** [comment]
@stevenmaske This has been submitted: https://github.com/microsoft/PowerPlatformConnectors/pull/3723

**Comment by troystaylor** [comment]
@vmanoharas Please close this issue.

**Comment by vmanoharas** [comment]
Sure @troystaylor
