### ISSUE TITLE
Logout does not work

### ISSUE THREAD

**Issue by daemel** [microsoft/PowerPlatformConnectors#376]
**Describe the bug**
Logout does not work 

**To Reproduce**
paconn logout

**Expected behavior**
logout from existing env 

**Environment summary**
c:\Users\daemel\Downloads\Code\repos>paconn --version
0.0.13

Python (Windows) 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]

Python location 'c:\users\*****l\appdata\local\programs\python\python38\python.exe'

**Additional context**
c:\Users\daemel\Downloads\Code\repos>paconn logout
usage: paconn [-h] [--verbose] [--debug] [--output {json,jsonc,table,tsv}] [--query JMESPATH]
              {login,download,create,update,validate} ...
paconn: error: argument _command: invalid choice: 'logout' (choose from 'login', 'download', 'create', 'update', 'validate')

**Comment by natalie-pienkowska** [comment]
@depfeife-msft when you're back from vacation, do you mind taking a look?

**Comment by RedsGT** [comment]
![image](https://user-images.githubusercontent.com/1190796/154894017-e47b61f6-085d-4e4b-b86a-eda347c1e9fa.png)
@mamurshe  Seems to work fine on 0.0.15
