### ISSUE TITLE
Not clear instructions for creating Facebook App especially requesting permissions

### ISSUE THREAD

**Issue by malkhawaja** [microsoft/PowerPlatformConnectors#399]
Hi,
after creating the custom connector i am facing errors in the actions, especially "post message to page" which requires extra permissions on the Facebook App check attached screenshot.
![SharedScreenshot](https://user-images.githubusercontent.com/43861985/91007199-048ee800-e5e4-11ea-9af6-9abbd2a01f99.jpg)

or am I doing it in a wrong way?

**Comment by mamurshe** [comment]
From your description and screenshot it appears you are doing it the right way. Unfortunately, Facebook requirements are beyond our control. Please contact Facebook if you have any question regarding the permission.
