### ISSUE TITLE
Client Certificate authentication in Custom Connector

### ISSUE THREAD

**Issue by Guustc** [microsoft/PowerPlatformConnectors#41]
We need to connect to a custom API through a proxy server thats need a client certificate for authentication. Also, the custom API it self needs Oauth 2 for handling the authentication.

So we have to types of authentication for 1 HTTP request.

Custom connectors do not support client certification at all and you are only able to choose 1 type of authentication.

**Describe the solution you'd like**
Maybe APIM Policy's for adding a client certificate? Like this: https://docs.microsoft.com/nl-nl/azure/api-management/api-management-authentication-policies#ClientCertificate

**Describe alternatives you've considered**
Normal HTTP request support client certificates, but then we need to manually do the oauth process which is not 100% secure.

**Comment by mamurshe** [comment]
@Guustc Thanks for the request. We include your request for future update.

**Comment by mamurshe** [comment]
@Guustc In the meantime I would encourage you to implement the feature. Please let me know if I can help in any way. I will close this issue for now.

**Comment by mlainez** [comment]
Hi, I'm having the same problem here. @mamurshe what did you mean by "I would encourage you to implement the feature", is there anything I can do?
