### ISSUE TITLE
Please add swagger validation exception for error code 202

### ISSUE THREAD

**Issue by sriyen-msft** [microsoft/PowerPlatformConnectors#446]
PR - https://github.com/microsoft/PowerPlatformConnectors/pull/439/checks?check_run_id=1102525157

Swagger validation is failed when partner is added an error code for '202' code. Can you please provide let us know why it is not supported. 

can you please add it to swagger validation exceptions as Partner is receiving 202 for some operations of their API.

**Comment by natalie-pienkowska** [comment]
@sriyen-msft can you please look into this bug and let us know if it's still valid?

**Comment by natalie-pienkowska** [comment]
@mamurshe will look to see if this is reflected in the current version of the swagger validator.
