### ISSUE TITLE
Issue in documentation of Planner Connector

### ISSUE THREAD

**Issue by yshkrishna** [microsoft/PowerPlatformConnectors#459]
Hi Team,

We have followed  [Document](https://github.com/microsoft/PowerPlatformConnectors/tree/dev/certified-connectors/Planner#planner-connector)  and now able to building the connector and found where the issue is present . 
 
It was mentioned in the above  [Document](https://github.com/microsoft/PowerPlatformConnectors/tree/dev/certified-connectors/Planner#planner-connector) which was incorrect,

> For API permissions, among other required permissions under "Microsoft Graph", please make sure "User.Read" is added. "User.Read" permission is required in order to login the current user and retrieve relevant information.

**Solution(Document need to be updated)**

We need to have any one of `Group.Read.All`,` Group.ReadWrite.All` permission and grant permission for APP to use planner as per [MS Document](https://docs.microsoft.com/en-us/graph/api/planneruser-list-tasks?view=graph-rest-1.0&tabs=http )

**Comment by mamurshe** [comment]
Thanks for reporting!

**Comment by natalie-pienkowska** [comment]
@yshkrishna We have taken in this documentation bug and will prioritize accordingly to ensure that it is completed.
