### ISSUE TITLE
paconn does not have logout

### ISSUE THREAD

**Issue by Cloudmersive** [microsoft/PowerPlatformConnectors#60]
**Is your feature request related to a problem? Please describe.**
If you login to paconn with account A and then want to login to paconn with account B there is actually no way to do this.  Running paconn login again tells you you are already logged in.  Running paconn logout does not exist as a command

**Describe the solution you'd like**
Add paconn logout or allow paconn login to be run while you are already logged in

**Comment by garrytrinder** [comment]
+1

Not a fix but a potential workaround, you can run multiple instances of paconn at the same time using a Docker container, each authenticated with different tenants, as shown below.

![image](https://user-images.githubusercontent.com/11563347/61034115-91fd8180-a3bc-11e9-9e72-1443cc9d2b03.png)

As the containers are isolated from each other they don’t conflict.

I have a public image on Docker Hub for re-use

https://hub.docker.com/r/garryt/paconn-cli

![image](https://user-images.githubusercontent.com/11563347/61034676-9b3b1e00-a3bd-11e9-825b-8a6d5b7df302.png)

It might also be possible (easier) to just run paconn in another terminal/shell window ☺️

**Comment by Cloudmersive** [comment]
Thanks @garrytrinder but running in Docker containers is pretty heavy for a basic script.

For reference the Zapier platform CLI has "zapier login" and "zapier logout".  This seems like a more sustainable solution to a basic problem.

**Comment by hdanzl** [comment]
The token is persisted in your {user}\.paconn folder. Just delete the file...

**Comment by Cloudmersive** [comment]
@hdanzl Good workaround, thanks.  Still seems like a built in logout command would be the right solution long term

**Comment by Cloudmersive** [comment]
Any plans to fix this?  It is causing issues that you cannot logout

**Comment by mamurshe** [comment]
A new release contains a fix for this issue. The login method now contains a --force parameter to override previous login. It will be posted to pypi by the end of next week.

**Comment by mamurshe** [comment]
Please delete the .paconn folder in the user directory to force it to login again.

**Comment by mamurshe** [comment]
0.0.11 is released with a --force option for login, which essentially discards previous login and logs the user in again. Please run `pip install --upgrade paconn` to update your version.

**Comment by Cloudmersive** [comment]
This works, thank you
