### ISSUE TITLE
"On all new alerts" trigger fires continuously

### ISSUE THREAD

**Issue by tmmueller** [microsoft/PowerPlatformConnectors#63]
**Describe the bug**
I created a very simple flow with the "On all new alerts" trigger. Unfortunately, the trigger fires every 2 minutes and outputs the same 20 alerts.

**To Reproduce**
Create a flow with the "On all new alerts" trigger. Watch what happens.

**Expected behavior**
The flow should run only when there are new alerts, and it should never run on the same alert more than once.

**Environment summary**
Microsoft Flow

**Additional context**
Screenshot of flow:

![image](https://user-images.githubusercontent.com/1289959/63487587-7f717000-c471-11e9-9e41-5ae9876777ef.png)

**Comment by mamurshe** [comment]
Hi @tmmueller please submit flow related issues to Microsoft Flow support: https://preview.flow.microsoft.com/en-us/support/
