### ISSUE TITLE
CSRF Token Validation Failed

### ISSUE THREAD

**Issue by iamforgit** [microsoft/PowerPlatformConnectors#660]
**Describe the bug**
I am connecting to SAP Demo System using Power Automate and OData connector. I am able to fetch the products successfully but while adding product I am getting error :  CSRF Token validation failed. 
**To Reproduce**
Steps to reproduce the behavior.
Step 1: I am creating a flow manual start action (for testing purpose, using power apps action also gives same error).
Step 1 : Add ListProuctSet action
Step 3 : Add product set action with set cookies and headers like this : replace(outputs('List_product_sets')?['headers/Set-Cookie'],',',';')
Step 4: run flow
**Expected behavior**
It should add new product in SAP system

**Comment by iamforgit** [comment]
Anyone had answer to this?

**Comment by ccpauto** [comment]
Hi @iamforgit 
Please post any connector related question here: https://powerusers.microsoft.com/t5/Connecting-To-Data/bd-p/ConnectingToData
