### ISSUE TITLE
[paconn] Allow client credentials authentication

### ISSUE THREAD

**Issue by edguer** [microsoft/PowerPlatformConnectors#678]
**Use case**
As a developer, I want to be able to run `paconn` from inside my DevOps pipelines. For that, I need to use an AAD Service Principal for authentication, allowing for `paconn` to run with no user interaction in a transient environment (e.g.: a short-lived Docker container).

**Additional context**
As of today, `paconn` only supports device authentication, which requires user interaction - subsequent operations won't prompt for login, but then it requires a persistent environment for caching the token. Support for client credentials authentication would allow running `paconn` with no user interaction, making it possible to use it in several DevOps solutions (e.g.: ADO, Github Actions, Jenkins, Bamboo and so on).

**How it could work**
By having an additional `--client_secret` flag on `login` command, we could switch from device authentication to client credentials authentication.  In [profile.py](https://github.com/microsoft/PowerPlatformConnectors/blob/dev/tools/paconn-cli/paconn/authentication/profile.py) we could have an additional function, such as:

```python
    def authenticate_client_credentials(self):
        """
        Do some stuff ...
        """
        mgmt_token = context.acquire_token_with_client_credentials(
            resource=self.resource,
            client_id=self.client_id,
            client_secret=self.client_secret)

        """
        Do some more stuff ...
        """

        return credentials.token
```

And, in [auth.py](https://github.com/microsoft/PowerPlatformConnectors/blob/dev/tools/paconn-cli/paconn/authentication/auth.py):
```python
        if profile.client_secret:
            credentials = profile.authenticate_client_credentials()
        else:
            credentials = profile.authenticate_device_code()
```

**Comment by hajekj** [comment]
This would be very nice, however, Flow RP API currently doesn't support Service Principal authentication. The only way which we figured out for publishing custom connectors with client_credentials flow is via packaged solution and deploy via PackageDeployer or similar [tools](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools).

**Comment by mamurshe** [comment]
@hajekj is correct. Although we are aware of this, currently we don't have a plan to add this scenario at this moment.

**Comment by schabungbam** [comment]
@edguer , @hajekj  - If you guys can submit a PR, we can definitely roll that in.

**Comment by natalie-pienkowska** [comment]
@edguer Thank you again for kicking off this conversation. We have added this to our backlog and will prioritize accordingly.
