### ISSUE TITLE
Array name gets put before field name/renaming arrays in custom connector

### ISSUE THREAD

**Issue by dk-klein** [microsoft/PowerPlatformConnectors#745]
Hello,
I have been creating a custom connector and I came upon an issue. When I define an array, custom connector automatically names fields after that array, which creates mess and is basically unusable/unreadable.
Example of OpenApi definition:
![image](https://user-images.githubusercontent.com/74151269/112982171-74f27e80-915c-11eb-8a67-357b48163815.png)
And how it looks in the custom connector:
![image](https://user-images.githubusercontent.com/74151269/112982298-9eaba580-915c-11eb-9742-2065408875aa.png)
As you can see, name of the array (People) is put before every single field. And when another array is defined (positions), it get put there too, making even more mess. 
Any suggestion on how to fix this?

**Comment by ccpauto** [comment]
Please post UI issues in the power automate forum: https://powerusers.microsoft.com/t5/General-Power-Automate/bd-p/MPAForum
