### ISSUE TITLE
Localization of Custom Connectors

### ISSUE THREAD

**Issue by hajekj** [microsoft/PowerPlatformConnectors#762]
We would like to distribute a custom connector in a solution with multiple languages (primarily labels, descriptions etc.) - how can we include translations with the Swagger definition?

Reference #274

**Comment by ccpauto** [comment]
Hi @hajekj 
I am not sure custom connector supports multiple language at this moment. Please feel free to add your idea to the forum: https://powerusers.microsoft.com/t5/Power-Automate-Ideas/idb-p/MPAIdeas
