### ISSUE TITLE
400 Client Error: Missing Object ID

### ISSUE THREAD

**Issue by coldcanuk** [microsoft/PowerPlatformConnectors#791]
**Describe the bug**
Following Microsoft/PowerPlatformConnectors/AzureKeyVault Recipe

Created new AppRegistration as per step-by-step guide in docs.microsoft.com referenced on the github article, added the permissions
Downloaded the two JSON files, the api definitions and the api properties, modified the data inside to match the clicks I made on my side. 
As per the recipe I run this command to create: 

`paconn create --api-def apiDefinition.swagger.json --api-prop apiProperties.json --secret "Foo********Bar"`

and I get this error. 
Please select an environment:
 **[1] Default Environment
Environment selected: Default Environment
{
  "error": {
    "code": "MissingObjectId",
    "message": "The provided object identifier was null or missing."
  }
}
400 Client Error: Bad Request for url: https://api.powerapps.com/providers/Microsoft.PowerApps/objectIds/validateApiSwagger?api-version=2016-11-01**
The same error happens when I try and validate with the command below
`paconn validate --api-def apiDefinition.swagger.json`

Line 3 of teh apidefinition.swagger.json file looked suspicious considering i'm getting an object message. 
```
{
  "basePath": "/",
  "consumes": [],
```
&& to triple check I pasted the file in an online json formatter and it confirmed it was a valid format.. so it's not a typo...
I read over the docs to make sure I didn't miss a click in portal.azure; and my _user eyes_ say followed each step and started over a few times. 
Frustrating to be hung up on the equivalent to **Hello World** -> your help and time is greatly appreciated!!!!

Cheers, 
~C

**Comment by mamurshe** [comment]
Sounds like you don't have access to the default environment for connector creation. Please try another environment or let us know if you do have access to the environment. You can specify the environment with `-e [GUID]` in the command line as well.

**Comment by natalie-pienkowska** [comment]
Response was provided. In the future, please submit connector development questions to the forum: https://powerusers.microsoft.com/t5/Connector-Development/bd-p/ConnectorDevelopment
