### ISSUE TITLE
paconn tool does not have a way to create zip file, even though instructions say to do this

### ISSUE THREAD

**Issue by Cloudmersive** [microsoft/PowerPlatformConnectors#80]
**Describe the bug**
The instructions in the connector certification portal say: "Please use the CLI Tool to create the zip file containing your connector artifacts. Documentation on this process can be found here."

However, this is not possible because paconn has no way of outputting a zip file

**Expected behavior**
Provide paconn package command that outputs a zip file.  Right now paconn download makes a folder, but not a zip file.  The website actually requires a zip file.

**Comment by mamurshe** [comment]
The paconn tool doesn't create a zip file at this moment. The document will be updated to reflect this.

**Comment by Guilhermeslucas** [comment]
Is this something we want to implement? I can help with that!

**Comment by mamurshe** [comment]
@Guilhermeslucas please feel free to implement this command.

**Comment by natalie-pienkowska** [comment]
@Cloudmersive We will create an internal documentation bug for this and prioritize internally. Thanks again!
