### ISSUE TITLE
Got error while pushing code in dev branch

### ISSUE THREAD

**Issue by asitedeveloper** [microsoft/PowerPlatformConnectors#822]
I am getting error while pushing file into dev branch. 
Please help us to identify the solution.

![image](https://user-images.githubusercontent.com/77782776/118133276-48e64080-b41e-11eb-8664-2667f024e5c2.png)

**Comment by mamurshe** [comment]
Please ignore if the issue is in our repo. If the issue is in your fork, please disable this job.
