### ISSUE TITLE
Office 365 Groups connector only returns 100 results

### ISSUE THREAD

**Issue by loryanstrant** [microsoft/PowerPlatformConnectors#826]
I know that the returning of 100 results is a limitation of the Graph call, however part of the response includes the odata.nextLink which has the URL to get the next batch of 100.
Any suggestions on how to make that work with the connector?

**Comment by natalie-pienkowska** [comment]
Hi @loryanstrant thanks for submitting this issue! The purpose of this repository is for custom connector submission. For questions, ideas, or feedback on existing Microsoft 1st party connectors, please go to the Power Automate forums. Thank you so much!

**Comment by loryanstrant** [comment]
Thanks Natalie, but the issue/feedback isn't with the first-party connector.
This custom connector could easily be updated to handle the pagination by creating an action that takes in the skiptoken, with some guidance around how to utilise this.

**Comment by natalie-pienkowska** [comment]
@loryanstrant For questions, ideas, or feedback on building a custom connector, please submit here: https://powerusers.microsoft.com/t5/Connector-Development/bd-p/ConnectorDevelopment
