### ISSUE TITLE
Instagram Professional Connector Outdated

### ISSUE THREAD

**Issue by MrFearLess98** [microsoft/PowerPlatformConnectors#835]
Hello everyone,

I am building a flow in Power Automate to fetch the comments of a post that is related to my Instagram account. After the data is fetched I would like to store these comments in a dataverse entity.

I did all the configuration steps before testing the custom connector based on my IG ID and I am encountering the below issue:

![Capture](https://user-images.githubusercontent.com/52073639/119137984-0f2ebe80-ba4a-11eb-993c-2cd979d3f1b6.PNG)

As an expected result, it should find my IG ID that I provided and fetch the data that are assigned in the fields of the connector.
As for the API version that is used in that customer connector, it’s V7.0 whereas the current one is v10.0.

Besides, the query parameters that are used in the actions of that custom connector are outdated and changed in the Instagram official documentation of the for example the media node fields.

Any idea why this problem occurs?

Your help will be highly appreciated.

Thank you!

**Comment by natalie-pienkowska** [comment]
Hi @MrFearLess98 thanks for submitting this issue! The purpose of this repository is for custom connector submission. For questions, ideas, or feedback on building a custom connector, please submit here: https://powerusers.microsoft.com/t5/Connector-Development/bd-p/ConnectorDevelopment
