### ISSUE TITLE
Dynamic Schema not respecting the Definitions reference

### ISSUE THREAD

**Issue by nk-gears** [microsoft/PowerPlatformConnectors#866]
**Describe the bug**
When using Dynamic schema, the "$ref":"#/definitions/<ModelName> is considering as a Invalid OpenAPI.

![image](https://user-images.githubusercontent.com/897323/121198591-e0a94400-c88f-11eb-8382-60e6ed389949.png)

**To Reproduce**
Steps to reproduce the behavior.
- Create a Dynamic Schema and a a reference to a existing Model in the Definition

**Expected behavior**
- If this feature is not implemented then add a note in the documentation that dynamic schema doesn't support the usage of ref

**Comment by natalie-pienkowska** [comment]
@nk-gears Thanks for submitting this bug. If you have submitted a certified connector to this repository, please send over the issue in an email to your certification contact. If you are not a certified connector owner, please submit this issue to this forum: https://powerusers.microsoft.com/t5/Connector-Development/bd-p/ConnectorDevelopment

Thank you :)

**Comment by nk-gears** [comment]
Thank you Natalie. Closing this
