### ISSUE TITLE
Generic OAuth 2.0 & Azure B2C protected API's

### ISSUE THREAD

**Issue by akhileshnirapure** [microsoft/PowerPlatformConnectors#885]
Hi,

We have couple of APIs published via APIM and is protected with JWT Policy (validated against by **Azure AD B2C tenant (A)** using **user flow**. The user flow has following key configurations

1. It is configured with an Azure AD IdP of M365 tenant (B) [[OpenID Connect]](https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-azure-ad-single-tenant?pivots=b2c-user-flow) 
2. It emmits extension property as part of successfull authentication. [[as per aad b2c]](https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-flow-custom-attributes?pivots=b2c-user-flow)

I'm creating a custom connector in Power Apps web console in M365 **Tenant B**, 

1. Uses authentication type as OAuth2.
2. Identity Provider -> Generic OAuth 2

I'm providing all the required values from Azure b2C **Tenant A**
1. ClientId - The client id of Azure AD b2c 
2. Secret - secret of AAD Application Azure AD b2c 
3. Authorization URL - https://tenanta.b2clogin.com/tenanta.onmicrosoft.com/user_flow_policy_id/oauth2/v2.0/authorize
4. Token URL - https://tenanta.b2clogin.com/tenanta.onmicrosoft.com/user_flow_policy_id/oauth2/v2.0/token
5. Refresh URL - https://tenanta.b2clogin.com/tenanta.onmicrosoft.com/user_flow_policy_id/oauth2/v2.0/token
6. Scope - openid offline_access

_Note_: the redirect url generated is already added in Client ID (in Azure AD b2c Tenant A)

**To test**
1. creating a new connection, which redirects us to B2C user flow endpoint and user is able to pick Tenant B to sign-in, the user connection is created fine.
2. Invoke action. --> here authorization token received but the call to back is not successfull. (i beleive this is on-behalf-of call from Tenant B to Tenant A via APIM policy)

![image](https://user-images.githubusercontent.com/5601155/122032521-01155900-cdd0-11eb-81c6-78bd12045a80.png)

No response or error received, the call doesn't go to backend API 

![image](https://user-images.githubusercontent.com/5601155/122032733-33bf5180-cdd0-11eb-955b-aa0864998d77.png)

Question
1. Do you support Azure B2C in such case?
2. Does the proxy (connector) obtains the additional claim/attribute when it makes call on behalf of user (after connection is established)?

**Comment by natalie-pienkowska** [comment]
Hi @akhileshnirapure thanks for submitting a bug! This repository is for submitting a custom connector, certified connector, or independent publisher connector. To get help on issues with building a custom connector, please submit your issue/question/feature request here: https://powerusers.microsoft.com/t5/Connector-Development/bd-p/PA-ConnectorDevelopment

**Comment by natalie-pienkowska** [comment]
Closing as this issue belongs in the forum
