### ISSUE TITLE
connectionParameters section (in apiProperties.json) is dropped when Custom Connector is imported from Github

### ISSUE THREAD

**Issue by dev-ng** [microsoft/PowerPlatformConnectors#948]
**Type of Connector**
- [x] custom 

**Name of Connector**
NSF Data

**Describe the bug**
This Connector uses a dynamic host policy. The policy is correctly implemented in apiProperties.json with parameter definition  in "connectionParameters" and it's use in "policyTemplateInstances".

However, if I create a new Custom Connector using "Import from Github" option the Host parameter is missing in the "New connection" dialog.
![new-connection-no-host](https://user-images.githubusercontent.com/21314227/125425787-c5aba80e-b980-4cc7-808d-cd55d5349aa7.png)

**Is this a security bug?**
- [x] no

**What is the severity of this bug?**
- [x] severity 1: Connector is broken or there's a very serious issue

**To Reproduce**
1. From PowerApps->Data->Custom Connectors->New custom connector -> Import from Github 
"Custom"
"master"
"NSF Data"
2. "Create connector"
3. "4. Test" -> New connection
4. Field "Host (with https/http)" is missing in dialog

**Expected behavior**
Dynamic host option (Field "Host (with https/http)") should be available once Connector is imported from GitHub and saved.

**Environment summary**
Install Method: From PowerApps->Data->Custom Connectors->New custom connector -> Import from Github

**Additional context**
First I checked the Policy "Dynamic host". It is available under "3. Definition".
![policy-ok](https://user-images.githubusercontent.com/21314227/125425788-e1816ebf-bfca-4997-8520-ac7d3bae4732.png)

Then I downloaded the apiProperties.json using paconn and discovered that the "connectionParameters" section is missing there. The "policyTemplateInstances" section is OK.

I manually added the missing "connectionParameters" (took from Github) and updated the Connector with "paconn" and the Connector works as expected - the Dynamic Host parameter is present in the dialog.
![new-connection-host-ok](https://user-images.githubusercontent.com/21314227/125425783-d3252c62-d7ef-446e-8289-53b7de3f4582.png)

I think it's a bug in the "Import from Github". Can this be fixed please?

**Comment by natalie-pienkowska** [comment]
Thanks for submitting this bug! I'll engineers will look into this for you :)

**Comment by philglew** [comment]
@dev-ng Does this bug appear no matter which environment you try to use this connector in?

**Comment by dev-ng** [comment]
> @dev-ng Does this bug appear no matter which environment you try to use this connector in?
Yep, reproduced just now in a different environment.

**Comment by dev-ng** [comment]
Hi @porterhunley , @philglew , @natalie-pienkowska ,
Any update on the status/resolution for this issue? It's still reproducible in different environments.

**Comment by porterhunley** [comment]
Hey @dev-ng , you should see the fix in two to three weeks depending on your location

**Comment by dev-ng** [comment]
Issue is fixed. Thanks!
